name: Flatpak Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flatpak:
    name: Flatpak Builder
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:elementary-8
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@6.7
        with:
          bundle: com.github.gylangsatria.clipstory.flatpak
          manifest-path: com.github.gylangsatria.clipstory.yml
          run-tests: false
          repository-name: appcenter
          repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          branch: stable
          build-bundle: true
          cache: true
          cache-key: flatpak-builder-${{ github.sha }}
          upload-artifact: true
